#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""                 stockContract
Created on Tue Nov 29 09:34:52 2016

@author: dmcauslan

Holds constants for the stock database

@author: fega

Modified 04/03/2020:
    * Table adapted and added a dim table for stocks
"""

## Transactions table
# Table Name
TRANSACTIONS_TABLE_NAME = "FACT_TRANSACTIONS"

# Table Columns
TRANSACTION_ID = "TRANSACTION_ID"
DATE = "DATE"
INSTRUMENT_BOUGHT = "INSTRUMENT_BOUGHT"
QUANTITY_BOUGHT = "QUANTITY_BOUGHT"
INSTRUMENT_SOLD = "INSTRUMENT_SOLD"
QUANTITY_SOLD = "QUANTITY_SOLD"
COMMISSION = "COMMISSION"

TRANSACTIONS_COLUMNS = [TRANSACTION_ID, DATE, INSTRUMENT_BOUGHT, QUANTITY_BOUGHT, INSTRUMENT_SOLD, QUANTITY_SOLD, COMMISSION]
TRANSACTIONS_COLUMN_LIST = "{} DATE,{} TEXT,{} REAL,{} TEXT,{} REAL,{} REAL".format(TRANSACTION_ID, DATE, INSTRUMENT_BOUGHT, QUANTITY_BOUGHT, INSTRUMENT_SOLD, QUANTITY_SOLD, COMMISSION)

## Information about the stocks
# Table Name
STOCKS_TABLE_NAME = "DIM_STOCKS"

# Table Columns
NAME = "NAME"
IB_TICKER = "IB_TICKER"
IB_EXCHANGE = "IB_EXCHANGE"
IB_CURRENCY = "IB_CURRENCY"
ISIN = "ISIN"
LINK_1 = "LINK_1"
LINK_2 = "LINK_2"
ICTAX_LINK = "ICTAX_LINK"
FUND_DOMICILE = "FUND_DOMICILE"
GOOGLE_FINANCE_SYMBOL = "GOOGLE_FINANCE_SYMBOL"
YAHOO_SYMBOL = "YAHOO_SYMBOL"
YAHOO_CURRENCY = "YAHOO_CURRENCY"

STOCKS_COLUMNS = [NAME, IB_TICKER, IB_EXCHANGE, IB_CURRENCY, ISIN, LINK_1, LINK_2, ICTAX_LINK, FUND_DOMICILE, GOOGLE_FINANCE_SYMBOL, YAHOO_SYMBOL, YAHOO_CURRENCY]

STOCKS_COLUMN_LIST = "{} TEXT, {} TEXT, {} TEXT, {} TEXT, {} TEXT, {} TEXT, {} TEXT, {} TEXT, {} TEXT, {} TEXT, {} TEXT, {} TEXT".format( NAME, IB_TICKER, IB_EXCHANGE, IB_CURRENCY, ISIN, LINK_1, LINK_2, ICTAX_LINK, FUND_DOMICILE, GOOGLE_FINANCE_SYMBOL, YAHOO_SYMBOL, YAHOO_CURRENCY)

## Historical prices table
# Table Name
HISTORICAL_TABLE_NAME = "FACT_HISTPRICES"

DATE = "DATE"
IB_TICKER = "IB_TICKER"
PRICE = "PRICE"

HISTORICAL_COLUMNS = [DATE, IB_TICKER, PRICE]

HISTORICAL_COLUMN_LIST = "{} DATE, {} TEXT, {} REAL".format(DATE, IB_TICKER, PRICE)

## Dividends data table contract
# Table Name
DIVIDEND_TABLE_NAME = "FACT_DIVIDENDS"

# Table Columns
DIVIDEND_DATE = "DIVIDEND_DATE"    
IB_TICKER = "IB_TICKER"    
DIVIDEND_AMOUNT = "DIVIDEND_AMOUNT"    
       
 
DIVIDEND_COLUMNS = [DIVIDEND_DATE, IB_TICKER, DIVIDEND_AMOUNT]  
   
DIVIDEND_COLUMN_LIST =  "{} DATE, {} TEXT, {} REAL".format(DIVIDEND_DATE,  IB_TICKER,  DIVIDEND_AMOUNT)